esphome:
  name: bb8-controller

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Bluetooth tracker for finding the BB-8
esp32_ble_tracker:

ble_client:
  - mac_address: D0:0E:71:8D:94:C7
    id: bb8_client
    auto_connect: false

external_components:
  - source:
      type: local
      path: components

sphero_bb8:
  id: bb8_hub
  ble_client_id: bb8_client
  auto_connect: false

light:
  - platform: sphero_bb8
    id: rgb_light
    name: "BB8 Main LED"
    sphero_bb8_id: bb8_hub
    type: RGB
    default_transition_length: 1s

  - platform: sphero_bb8
    id: tail_light
    name: "BB8 Tail Light"
    sphero_bb8_id: bb8_hub
    type: TAILLIGHT
    default_transition_length: 500ms

button:
  - platform: sphero_bb8
    name: "BB8 Connect"
    sphero_bb8_id: bb8_hub
    type: CONNECT

  - platform: sphero_bb8
    name: "BB8 Disconnect"
    sphero_bb8_id: bb8_hub
    type: DISCONNECT

  - platform: sphero_bb8
    name: "BB8 Center Head"
    sphero_bb8_id: bb8_hub
    type: CENTER_HEAD

text_sensor:
  - platform: sphero_bb8
    name: "BB8 Connection Status"
    sphero_bb8_id: bb8_hub
    firmware_version:
      name: "BB8 Firmware Version"
    charging_status:
      name: "BB8 Charging Status"

binary_sensor:
  - platform: sphero_bb8
    name: "BB8 Collision"
    id: bb8_collision

sensor:
  - platform: sphero_bb8
    battery_level:
      name: "BB8 Battery Level"
    collision_speed:
      name: "BB8 Collision Speed"
    collision_magnitude:
      name: "BB8 Collision Magnitude"


